openapi: 3.0.0
info:
  title: Book API Documentation
  version: 1.0.0
  description: Book API Information
servers:
  - url: http://localhost:5000
    description: Development server

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session

paths:
  /signup:
    post:
      tags:
        - Authentication
      summary: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - fullName
                - password
                - phone
                - address
                - coordinates
              properties:
                email:
                  type: string
                  format: email
                fullName:
                  type: string
                password:
                  type: string
                phone:
                  type: string
                address:
                  type: string
                coordinates:
                  type: array
                  items:
                    type: array
      responses:
        '200':
          description: User created successfully
          
          
  /signin:
    post:
      tags:
        - Authentication
      summary: Sign in to user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: User signed in successfully

  /profile:
    get:
      tags:
        - Users
      summary: Get current user's profile
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
        '401':
          description: Unauthorized

  /books:
    post:
      tags:
        - Books
      summary: Add a new book
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - author
                - publishedYear
                - description
                - category
                - condition
                - price
                - quantity
                - imageUrl
              properties:
                title:
                  type: string
                author:
                  type: string
                publishedYear:
                  type: number
                description:
                  type: string
                category:
                  type: string
                  enum: [Engineering, Diploma, Other]
                condition:
                  type: string
                  enum: [Like New, Good, Fair, Poor]
                price:
                  type: number
                quantity:
                  type: number
                imageUrl:
                  type: string
      responses:
        '201':
          description: Book created successfully
        '401':
          description: Unauthorized

    get:
      tags:
        - Books
      summary: Get books near user's location
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Books retrieved successfully
        '401':
          description: Unauthorized

  /search:
    get:
      tags:
        - Books
      summary: Search books with filters
      security:
        - cookieAuth: []
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: Search query
        - in: query
          name: searchBy
          schema:
            type: string
            enum: [all, title, author, publisher]
          description: Field to search by
        - in: query
          name: category
          schema:
            type: string
            enum: [all, Engineering, Diploma, Other]
        - in: query
          name: condition
          schema:
            type: string
            enum: [all, Like New, Good, Fair, Poor]
        - in: query
          name: year
          schema:
            type: string
      responses:
        '200':
          description: Books retrieved successfully
        '401':
          description: Unauthorized

  /book/{id}:
    get:
      tags:
        - Books
      summary: Get book details by ID
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Book ID
      responses:
        '200':
          description: Book details retrieved successfully
        '401':
          description: Unauthorized
        '404':
          description: Book not foundxx